/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import model.AppModelTest;
	import model.ObjectsLocationModelTest;
	import model.SimplePackerTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var model_SimplePackerTest_obj:model.SimplePackerTest;
		
		private var model_ObjectsLocationModelTest_obj:model.ObjectsLocationModelTest;
		private var model_AppModelTest_obj:model.AppModelTest;
	}
}